# Generated by Django 5.2 on 2025-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "codigoCarro",
                    models.SmallAutoField(
                        db_column="CodigoCarro",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código Interno",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        db_column="Modelo",
                        max_length=50,
                        verbose_name="Modelo do Carro",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        db_column="Marca", max_length=50, verbose_name="Marca do Carro"
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(db_column="Ano", verbose_name="Ano do Carro"),
                ),
                (
                    "cor",
                    models.CharField(
                        db_column="Cor", max_length=20, verbose_name="Cor do Carro"
                    ),
                ),
                (
                    "dataEntrada",
                    models.DateField(
                        db_column="DataEntrada", verbose_name="Data de Entrada"
                    ),
                ),
                (
                    "combustivel",
                    models.CharField(
                        choices=[
                            ("G", "Gasolina"),
                            ("E", "Etanol"),
                            ("D", "Diesel"),
                            ("F", "Flex"),
                            ("ET", "Elétrico"),
                            ("H", "Híbrido"),
                        ],
                        db_column="Combustivel",
                        max_length=20,
                        verbose_name="Tipo de Combustível",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carro",
                "verbose_name_plural": "Carros",
                "db_table": "Carro",
                "ordering": ["modelo"],
            },
        ),
    ]
